# Generated by Django 3.2.18 on 2023-03-09 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20230309_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Количество ингредиента в рецептe', 'verbose_name_plural': 'Количество ингредиентов в рецептах'},
        ),
    ]
