# Generated by Django 3.2.18 on 2023-03-12 14:38

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230306_1837'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='Вы не можете подписаться на себя',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(check=models.Q(('subscriber', django.db.models.expressions.F('target')), _negated=True), name='no_self_subscription'),
        ),
    ]
